"use client";
import { useCallback, useEffect, useState } from "react";
type Firm = { id:string; employer:string; highFit:boolean; location:string|null; distanceMiles:number|null; bucket?:string; careersUrl:string|null; verifiedInternships:number; lastCheckedAt:string|null; monitoringStatus:string; trustedReason:string; insideRadius:boolean; isRemote:boolean };
type Diagnostics = { approvedEmployersChecked:number; withVerifiedLocations:number; insideRadius:number; outsideRadius?:number; currentOfferingInternships:number; unknownLocations:number; lastCompletedScan:string; errors:string[] };
type Payload = { center:string; radiusMiles:number; firms:Firm[]; outsideRadius?:Firm[]; locationUnknown?:Firm[]; diagnostics:Diagnostics };
export default function LocalFirmsPage() {
  const [radius,setRadius]=useState(50), [data,setData]=useState<Payload|null>(null), [loading,setLoading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setData(await (await fetch(`/api/nearby-firms?radiusMiles=${radius}`)).json());setLoading(false)},[radius]);
  useEffect(()=>{load()},[load]);
  const firmCard = (f:Firm) => <article key={f.id} className={`bg-surface border rounded-lg p-4 ${f.employer==="L3Harris Technologies"?"border-verified-line ring-1 ring-emerald-200":"border-hairline"}`}><div className="flex justify-between gap-4"><div><h2 className="font-semibold">{f.employer}{f.highFit&&<span className="ml-2 text-xs text-verified">High EE/CPE fit</span>}</h2><p className="text-sm text-secondary">{f.location??"Location not yet verified"}{f.distanceMiles!=null?` · ${f.distanceMiles} miles from Clifton`:f.isRemote?" · Remote":" · Distance unknown"}</p>{f.careersUrl&&<a href={f.careersUrl} target="_blank" rel="noreferrer" className="text-xs text-accent-text hover:underline">Official careers website ↗</a>}<p className="text-xs text-tertiary mt-2">{f.trustedReason}</p></div><div className="text-right text-xs"><div className="font-semibold">{f.verifiedInternships} verified openings</div><div className="capitalize">{f.monitoringStatus}</div><div>{f.lastCheckedAt?`Checked ${new Date(f.lastCheckedAt).toLocaleString()}`:"Not checked yet"}</div></div></div></article>;
  return <div className="max-w-6xl mx-auto px-8 py-10 space-y-6"><header><h1 className="text-2xl font-semibold">Local Firms</h1><p className="text-sm text-secondary">Origin: <b>Clifton, New Jersey</b>. Only firms with a real computed distance within the radius appear here — distant firms (e.g. California) are excluded, and firms with no resolvable location go to Location Unknown. Distances use Haversine miles and are never invented.</p></header>
    <section className="bg-surface border rounded-lg p-4 flex items-end gap-4"><label className="space-y-1"><span className="block text-xs font-medium">Radius</span><select className="input" value={radius} onChange={e=>setRadius(Number(e.target.value))}>{[25,50,100,150].map(v=><option key={v} value={v}>{v} miles</option>)}</select></label><button onClick={load} className="rounded-lg bg-accent text-white px-4 py-2.5 text-sm">{loading?"Scanning…":"Refresh approved sources"}</button></section>
    {data&&<section className="grid grid-cols-2 md:grid-cols-3 gap-3">{[["Approved employers checked",data.diagnostics.approvedEmployersChecked],["Verified locations",data.diagnostics.withVerifiedLocations],[`Inside ${data.radiusMiles}mi`,data.diagnostics.insideRadius],["Outside radius",data.diagnostics.outsideRadius??0],["Offering internships",data.diagnostics.currentOfferingInternships],["Location unknown",data.diagnostics.unknownLocations]].map(([label,value])=><div key={String(label)} className="bg-surface border rounded-lg p-4"><div className="text-xs text-tertiary">{label}</div><div className="font-semibold">{value}</div></div>)}</section>}
    <div><h2 className="text-sm font-semibold text-secondary mb-2">Within {data?.radiusMiles} miles of Clifton, NJ ({data?.firms.length??0})</h2><div className="space-y-3">{data?.firms.length? data.firms.map(firmCard) : <p className="text-sm text-tertiary">No approved firms currently resolve to a location within {data?.radiusMiles} miles.</p>}</div></div>
    {data?.outsideRadius&&data.outsideRadius.length>0&&<details className="bg-surface border rounded-lg p-4"><summary className="cursor-pointer text-sm font-medium text-secondary">Outside the radius ({data.outsideRadius.length}) — excluded from Local Firms</summary><div className="space-y-3 mt-3">{data.outsideRadius.map(firmCard)}</div></details>}
    {data?.locationUnknown&&data.locationUnknown.length>0&&<details className="bg-surface border rounded-lg p-4"><summary className="cursor-pointer text-sm font-medium text-secondary">Location Unknown ({data.locationUnknown.length}) — no resolvable coordinates, never counted as local</summary><div className="space-y-3 mt-3">{data.locationUnknown.map(firmCard)}</div></details>}
  </div>;
}
